# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.infosecadvisers.com
title: InfoSec Advisers
email: arkadiyg@infosecadvisers.com
author: Arkadiy Goykhberg
description: > # "Write an awesome description for your new site here. 
  Cloud Security, Cloud Migration, and DevOps Transforation consulting.
copyright: 'Copyright &copy; 2016 InfoSec Advisers. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/arkadiyg
  - title: github
    url: https://github.com/arkadiyg
  - title: linkedin
    url: https://www.linkedin.com/in/arkadiyg
